#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';

const root = process.cwd();
const gitDir = path.join(root, '.git');
const hooksDir = path.join(gitDir, 'hooks');
if (!fs.existsSync(gitDir)) {
  console.error('No .git directory found. Run this from the repo root.');
  process.exit(1);
}
fs.mkdirSync(hooksDir, { recursive: true });

const hookPath = path.join(hooksDir, 'pre-push');
const content = `#!/bin/sh\n# Auto-generated by scripts/setup-hooks.mjs\n# Creates a context snapshot before each push (dev convenience)\nif command -v node >/dev/null 2>&1; then\n  NOTES=\"auto pre-push snapshot: $(git rev-parse --abbrev-ref HEAD)\"\n  node scripts/context-snapshot.mjs --notes \"$NOTES\" >/dev/null 2>&1 || true\nfi\nexit 0\n`;
fs.writeFileSync(hookPath, content, { mode: 0o755 });
console.log('Installed pre-push hook at', hookPath);

